import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { initialState } from './states';

// const initialState = {
//     status: 'idle',
//     users: [],
//     products: []
//   };
  
export const usersAsync = createAsyncThunk(
    'users/fetchUser',
    async () => {
      const response =  await fetch("https://jsonplaceholder.typicode.com/users");
      const data =  await response.json();
      console.log("Get async reducer users");
      console.log(data);
      return data;
    }
);

export const userSlice = createSlice({
    name: 'users',
    initialState,
        // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(usersAsync.fulfilled, (state, action) => {
          state.status = 'idle';
          state.users = action.payload;
        });
    },
});

export default userSlice.reducer;